env_id: NeedleReach-v0

hparams:
  polyak: 0.95
# HER
  replay_strategy: future
  replay_k: 4

#  Networks
  actor_layers:  [128, 256, 128]
  transition_net_layers: [128, 256, 128]
  value_net_layers: [128, 256, 128]

  actor_lr: 0.0003
  transition_net_lr: 0.0003
  value_net_lr: 0.0003
  alpha_lr: 0.0003

  alpha: auto
  gamma: 1.00
  beta: 0.99

#  available values list:
#  sac_maximize
#  sac_minimise
#  sac_minimize_entropy
#  adapted_daif
  efe_approximation_approach: sac_minimise

#  available values list:
#  SquashedDiagGaussianDistribution
#  StateDependentNoiseDistribution
  actor_action_distribution: SquashedDiagGaussianDistribution

#  available values list:
#  mlp
#  gru
#  lstm
  transition_network_type: lstm

#  available values list:
# Disentangled Beta-VAE
# LogCosh
# original
  vae_type: original
  observations_seq_len: 7 # default 3

vae:
  tb_log_folder: logs\vae\tensorboard\{experiment_name}
  hparams:
    memory_capacity: 50000
    batch_size: 4
    image_shape: [32, 32, 3]
    vae_seq_len: 4 # fixed, dont change

