env_id: "NeedleReach-v0"

print_timer: 100

hparams:
  polyak: 0.95
# HER
  replay_strategy: future
  replay_k: 4

#  Networks
  use_sde: False
  actor_layers:  [128, 256, 128]
  transition_net_layers: [128, 256, 128]
  value_net_layers: [128, 256, 128]

  actor_lr: 0.0003
  transition_net_lr: 0.0003
  value_net_lr: 0.0003
  alpha_lr: 0.0003

  noise_eps: 0.2
  random_eps: 0.3
  alpha: auto
  gamma: 1.00
  beta: 0.99

#  available values list:
#  sac_maximize
#  sac_minimise
#  sac_minimize_entropy
#  adapted_a2c
  efe_approximation_approach: sac_maximize

#  available values list:
#  SquashedDiagGaussianDistribution
#  StateDependentNoiseDistribution
#  DiagGaussianDistribution
  agent_action_distribution: SquashedDiagGaussianDistribution

#  available values list:
#  none - to test its impact
#  GRU
#  LSTM
  transition_network_type: none

#  available values list:
# Disentangled Beta-VAE
# LogCosh
# original
  vae_type: none
