experiment_name: NeedleGrasp-mlp-daif
experiment_description: "just to test reward"

#experiment_name: efe-as-sac-v15
#experiment_description: "use true alg"

monitor_file: logs\{experiment_name}\monitor.csv
tb_log_folder: logs\tensorboard\{experiment_name}
seed: 42

hparams:
  n_epochs: 200
  steps_per_epoch: 200
  n_training_iterations: 10
  n_rollout_episodes: 3
  n_warmap_episodes: 50

should_save_model: true
model_path: models\efe-as-sac-v17\epoch_49
model_save_timer: 10


should_save_episode_video: true
episode_video_timer: 5
video_log_folder: logs\gif\{experiment_name}

