experiment_name: efe-as-sac-v14
experiment_description: "learn alpha, hparams from baseline implementation"

monitor_file: logs\{experiment_name}\monitor.csv
tb_log_folder: logs\tensorboard\{experiment_name}
seed: 42

hparams:
  n_epochs: 50
  n_cycles: 50
  n_batches: 5
  n_episodes: 5

should_save_model: true
model_path: models\{experiment_name}
model_save_timer: 3


should_save_episode_video: true
episode_video_timer: 5
video_log_folder: logs\gif\{experiment_name}

