env_log_folder: "D:/2022/thesis/docs/logs/envs"
tb_log_folder: "D:/2022/thesis/docs/logs/tensorboard"
log_folder: "D:/2022/thesis/docs/logs/log"
seed: 42
start_timesteps: 5000
eval_freq: 10000
max_timesteps: 2.0e+5
ensemble_size: 15
hidden_size: 400
n_train_epochs: 100
batch_size: 64
learning_rate: 1e-3
epsilon: 1e-8
grad_clip_norm: 1000
plan_horizon: 15
optimisation_iters: 5
n_candidates: 500
top_candidates: 50
n_seed_episodes: 5
n_episodes: 100