experiment_name: temp
experiment_description: "test mdp sac with this task"

monitor_file: logs\{experiment_name}\monitor.csv
tb_log_folder: logs\tensorboard\{experiment_name}
seed: 42

hparams:
  n_epochs: 200
  steps_per_epoch: 200
  n_training_iterations: 10
  n_rollout_episodes: 10
  n_warmap_episodes: 50

should_save_model: true
model_path: models\{experiment_name}
model_save_timer: 10


should_save_episode_video: true
episode_video_timer: 5
video_log_folder: logs\gif\{experiment_name}

