experiment_name: efe-as-sac-v17
experiment_description: "fix her sampling"

#experiment_name: efe-as-sac-v15
#experiment_description: "use true alg"

monitor_file: logs\{experiment_name}\monitor.csv
tb_log_folder: logs\tensorboard\{experiment_name}
seed: 42

hparams:
  n_epochs: 50
  steps_per_epoch: 50
  n_training_iterations: 10
  n_rollout_episodes: 10
  n_warmap_episodes: 100

should_save_model: true
model_path: models\{experiment_name}
model_save_timer: 1


should_save_episode_video: true
episode_video_timer: 5
video_log_folder: logs\gif\{experiment_name}

