experiment_name: baseline-trik

monitor_file: logs\{experiment_name}\monitor.csv
tb_log_folder: logs\{experiment_name}\tensorboard
seed: 42

n_epochs: 50
n_cycles: 50
n_batches: 5
max_episode_steps: 10
n_episodes: 3

should_save_model: true
model_path: models\{experiment_name}
model_save_timer: 500

should_save_episode_video: true
episode_video_timer: 5